#
# Copyright 2011-2019 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx#license-bsd-2-clause
#

BGFX_DIR=../../bgfx
RP_DIR=../
RUNTIME_DIR=$(RP_DIR)/runtime
BUILD_DIR=../.build

#SHADERS_DIR=$(RP_DIR)/shaders

TARGET=1

include $(BGFX_DIR)/scripts/shader.mk
